#%RAML 0.8
title: Angular Generator Server
version: 1.0

/me:
  get:
    description: Get authorities for user logging in.
    responses:
      200:
        body:
          application/json:
            example: |
                { 
                  "id": "1",
                  "username": "john.doe",
                  "authorities": [ 
                                  "USER",
                                  "USER.EDIT",
                                  "USER.CREATE",
                                  "COMPANY",
                                  "COMPANY.EDIT",
                                  "COMPANY.CREATE"
                                 ]
                }
      401:
        description: Invalid username and password combination.
              
/companies:
  get:
    description: Get list of Company records.
    responses:
      200:
        body:
          application/json:
            example: |
              { 
                "elements":[
                              { "id": "1",
                                "contact":
                                { "name":
                                    { "first": "Karyn",
                                      "last": "Porter"
                                    },
                                  "email": "karyn.porter@stelaecor.com"
                                },
                                "name": "MARVAME",
                                "phone": "+1 (828) 533-2655"
                              },
                              { "id": "2",
                                "contact":
                                { "name":
                                    { "first": "Page",
                                      "last": "Williamson"
                                    },
                                  "email": "page.williamson@trollery.name"
                                },
                                "name": "BOILICON",
                                "phone": "+1 (893) 432-3827"
                              }
                           ],
                "_metadata": 
                  {
                    "totalElements": 2
                  }
              }
                                  
                                      
      403:
        description: Logged in user does not have either 'COMPANY', 'COMPANY.EDIT' or 'COMPANY.CREATE' role
  post:
    description: Create a new company.
    body:
      application/json:
        example: |
          { 
            "name": "Company name 3",
            "address": "Address 3",
            "phone": "Phone 3",
            "contact": 
                { "name":
                    { "last": "Lastname 3",
                      "first": "Firstname 3"
                    },
                  "email": "company3@gmail.com"
                }
          }
    responses:
      201:
        body:
          application/json:
            example: |
              { 
                "id": "3",
                "name": "Company name 3",
                "address": "Address 3",
                "phone": "Phone 3",
                "contact": 
                    { "name":
                        { "last": "Lastname 3",
                          "first": "Firstname 3"
                        },
                      "email": "company3@gmail.com"
                    }
              }
      403:
        description: The logged in user does not have 'COMPANY.CREATE' role
  /{id}:
    get:
      description: Get an individual Company record.
      responses:
        200:
          body:
            application/json:
              example: |
                {  
                  "name": "Company name 3",
                  "address": "Address 3",
                  "phone": "Phone 3",
                  "contact": 
                      { "name":
                          { "last": "Lastname 3",
                            "first": "Firstname 3"
                          },
                        "email": "company3@gmail.com"
                      }
                }
        403:
          description: The logged in user does not have either 'COMPANY', 'COMPANY.EDIT' or 'COMPANY.CREATE' role
        404:
          body:
            application/json:
              example: |
                { 
                  "error": "Not Found",
                  "message": "Company not found"
                }  
    put:
      description: Update an individual Company record
      body:
        application/json:
            example: |
              { 
                "name": "TALAE",
                "address": "New address",
                "phone": "+1 (816) 590-3053",
                "contact": 
                    { "name":
                        { "first": "Joseph",
                          "last": "Cherry"
                        },
                      "email": "joseph.cherry@venoflex.org"
                    }
              }
      responses:
        200:
          body:
            application/json:
              example: |
                  { 
                    "id": "2",
                    "name": "TALAE",
                    "address": "New address",
                    "phone": "+1 (816) 590-3053",
                    "contact": 
                        { "name":
                            { "first": "Joseph",
                              "last": "Cherry"
                            },
                          "email": "joseph.cherry@venoflex.org"
                        }
                  }
        403:
          description: The logged in user does not have either 'COMPANY.EDIT' or 'COMPANY.CREATE' role
        404:
          body:
            application/json:
              example: |
                { 
                  "error": "Not Found",
                  "message": "Company not found"
                }  
    delete:
      description: Delete an individual Company record
      responses:
        204:
        403:
          description: The logged in user does not have 'COMPANY.CREATE' role
        404: 
            body:
              application/json:
                example: |
                  { 
                    "error": "Not Found",
                    "message": "Company not found"
                  } 
/users:
  get:
    description: Get list of User records
    queryParameters:
      name:
        description: Returns the Users whose names contain this substring
      _orderBy:
        description: Returns the Users in order of this attribute ('name' or 'email')
      _pageNumber:
        description: Returns Users on this page number
        type: number
      _pageSize:
        description: Returns this many Users on each page
        type: number
    responses:
      200:
        body:
          application/json:
            example: |
             { 
               "elements": [
                              { "id":"8",
                                "name": "Clementina DuBuque",
                                "email": "Rey.Padberg@karina.com"
                              },
                              { "id":"3",
                                "name": "Ervin Howell",
                                "email": "Nathan@yesenia.net"
                              }
                           ],
              "_metadata":
                  { 
                    "totalElements": 2
                  }
             }
      403:
        description: Logged in user does not have either 'USER', 'USER.EDIT' or 'USER.CREATE' role
  post:
    description: Create a new User record.
    body:
      application/json:
        example: |
          { 
            "name": "New User",
            "email": "myEmail@gmail.com"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              { 
                "id": "8",
                "name": "New User",
                "email": "myEmail.gmail.com"
              }
      403:
        description: The logged in user does not have 'USER.CREATE' role
  /{id}:
    get:
      description: Get an individual User record.
      responses:
        200:
          body:
            application/json:
              example: |
                { 
                  "name": "New User",
                  "email": "myEmail.gmail.com"
                }
        403:
          description: The logged in user does not have either 'USER', 'USER.EDIT' or 'USER.CREATE' role
        404:
          body:
            application/json:
              example: |
                {
                  "error": "Not Found",
                  "message": "User not found"
                }
    put:
      description: Update an individual User record.
      body:
        application/json:
          example: |
            {
              "name": "New Name",
              "email": "new@email.com"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "6",
                  "name": "New Name",
                  "email": "new@email.com"
                }
        403:
          description: The logged in user does not have either 'USER.EDIT' or 'USER.CREATE' role
        404:
          body:
            application/json:
              example: |
                {
                  "error": "Not Found",
                  "message": "User not found"
                }
    delete:
      description: Delete an individual User record.
      responses:
        204:
        404:
          body:
            application/json:
              example: |
                {
                  "error": "Not Found",
                  "message": "User not found"
                }
        
        
      