create table contact (
	id bigint generated by default as identity, 
	email varchar(255),
	first_name varchar(255),
	last_name varchar(255),
	primary key (id)
);

create table company (
	id bigint generated by default as identity, 
	name varchar(255),
	phone varchar(20),
	contact_id bigint,
	primary key (id)
);

alter table company
add foreign key (contact_id) references contact(id);

insert into contact (email, first_name, last_name) values ('karyn.porter@stelaecor.com', 'Karyn', 'Porter');

insert into company (name, phone, contact_id) 
select 'MARVAME' as name, '+1 (828) 533-2655' as phone, id as contact_id
from contact
where email = 'karyn.porter@stelaecor.com';

insert into company (name, phone, contact_id) 
select 'BOILICON' as name, '+1 (893) 432-3827' as phone, id as contact_id
from contact
where email = 'karyn.porter@stelaecor.com';
