create table user (
	id bigint generated by default as identity, 
	username varchar_ignorecase(50) not null unique,
	password varchar(128) not null,
	name varchar(255) not null,
	email varchar(255) not null,
	primary key (id)
);

 create table role (
 	  id bigint generated by default as identity, 
      role_name varchar_ignorecase(50) not null unique);
      
create table user_role (
 	  user_id bigint not null,
 	  role_id bigint not null,
      foreign key(user_id) references user(id),
      foreign key(role_id) references role(id));
      
insert into role (role_name) values ('USER');
insert into role (role_name) values ('USER.EDIT');
insert into role (role_name) values ('USER.CREATE');
insert into role (role_name) values ('COMPANY');
insert into role (role_name) values ('COMPANY.EDIT');
insert into role (role_name) values ('COMPANY.CREATE');

insert into user (username, password, name, email) values ('a', '$2a$10$uq5uv8n/UXq7BjdYMTJuvuqOIC6ABD6vO0fYCGArtlKXlEUV1m2va', 'First User', 'firstUser@email.com');

insert into user_role(user_id, role_id)
select user.id as user_id, role.id as role_id
from user, role;