create table contact (
	id bigint generated by default as identity, 
	email varchar(255),
	first_name varchar(255),
	last_name varchar(255),
	primary key (id)
);

create table company (
	id bigint generated by default as identity, 
	name varchar(255),
	phone varchar(20),
	contact_id bigint,
	primary key (id)
);

alter table company
add foreign key (contact_id) references contact(id);